## Name: Aaryan Dhakal
## Student ID: 2505814

## Title: Sum of Sequences
## Description: This program calculates the sum of sequences generated by quest01 and quest02.

# Import the sequence function from quest01
from quest01 import sequence
# Import the method_one function from quest02
from quest02 import method_one


def sum_quest01():
    """
    Calculates the sum of the sequence generated by quest01.

    Returns:
        int: The sum of the sequence.
    """
    # Return the sum of the sequence generated by the sequence function from quest01
    return sum(sequence())


def sum_quest02():
    """
    Calculates the sum of the sequence generated by quest02.

    Returns:
        int: The sum of the sequence.
    """
    # Return the sum of the sequence generated by the method_one function from quest02
    return sum(method_one())


# Only runs when executed directly, not when imported in another file.
if __name__ == "__main__":
    # Print the sum of the sequence from quest01
    print(sum_quest01())
    # Print the sum of the sequence from quest02
    print(sum_quest02())
